version: '3'

services:
  vnc-desktop:
    image: linuxserver/webtop:ubuntu-xfce
    container_name: vnc-desktop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - KEYBOARD=en-us-qwerty
      - PASSWORD=password123
      - WEBPAGE_TITLE=VNC_Desktop
    ports:
      - "5000:3000"  # Web interface on port 5000
    volumes:
      - webtop_data:/config
    devices:
      - /dev/snd:/dev/snd  # Pass sound device to container if available
    restart: unless-stopped
    shm_size: 2gb

volumes:
  webtop_data:
